Vulnerability fix for `my-app`
drasi-project/learning pull request #10
Opened 2024-10-16 17:42 UTC by ruokun-niu

- Updated the version of `express`
- Updated alpine linux to use 3.19

2024-10-17 02:48 UTC, danielgerlag approved these changes

2024-10-18 13:42 UTC, agentofreality requested changes
@ruokun-niu this sample is unusable in its current form.

The k8s source has not been included in the drasi-platform repo.

For now, we should move this sample to our prototyping repo.

2024-10-18 16:06 UTC, ruokun-niu commented
> @ruokun-niu this sample is unusable in its current form.
> 
> The k8s source has not been included in the drasi-platform repo.
> 
> For now, we should move this sample to our prototyping repo.

Should we do this in a separate PR? There are some other sample apps that use a prototyping source/reaction

2024-10-22 20:40 UTC, agentofreality approved these changes

2024-10-22 21:58 UTC, merged